version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # setup and dep fetches
      - run: |
          # install Cue
          curl -LO https://github.com/cuelang/cue/releases/download/v0.2.0/cue_0.2.0_Linux_x86_64.tar.gz
          tar -xf cue_0.2.0_Linux_x86_64.tar.gz
          sudo mv cue /usr/local/bin/cue

          # fetch deps
          go mod vendor

      # hof build and test
      - run: |
          # run unit tests
          pushd ci/test > /dev/null
          cue -t unit run-tests
          popd > /dev/null

          # build hof
          go build -o hof cmd/hof/main.go
          sudo mv hof /usr/local/bin/hof

          # run cli tests
          pushd ci/test > /dev/null
          cd ci/test && cue -t cli run-tests
          popd > /dev/null

      # Scan and upload reports
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
