steps:

- name: 'gcr.io/cloud-builders/go:debian'
  args: [ 'mod', 'vendor']
  env:
    - 'PROJECT_ROOT=github.com/hofstadter-io/hof'

- name: 'gcr.io/cloud-builders/go:debian'
  args: [ 'build', '-o', 'hof-$BRANCH_NAME']
  env:
    - 'PROJECT_ROOT=github.com/hofstadter-io/hof'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'hof-$BRANCH_NAME', 'gs://hof-io--develop-internal/hof/hof-$BRANCH_NAME']


