steps:

- name: 'gcr.io/cloud-builders/go:debian'
  args: [ 'build', '-o', 'hof-$TAG_NAME']
  env:
    - 'PROJECT_ROOT=github.com/hofstadter-io/hof'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'hof-$TAG_NAME', 'gs://hof-io--develop-internal/hof/hof-$TAG_NAME']

