name: default
"on":
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.19.x
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build CLI
        run: go install ./cmd/hof
      - name: Run self-gen test
        run: hof flow @test/gen ./test.cue
      - name: Run render tests
        run: hof flow @test/render ./test.cue
      - name: Run lib/structural tests
        run: hof flow @test/st ./test.cue
    services: {}
