name: fmt
"on":
  workflow_dispatch: {}
  push:
    paths:
      - lib/fmt/**
      - formatters/**
      - .github/workflows/fmt.*
  pull_request:
    paths:
      - lib/fmt/**
      - formatters/**
      - .github/workflows/fmt.*
jobs:
  formatter:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        formatter:
          - prettier
          - csharpier
          - black
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Vars
        id: vars
        run: |-
          SHA=${GITHUB_SHA::8}
          TAG=$(git tag --points-at HEAD)
          echo "HOF_FMT_VERSION=${TAG}" >> $GITHUB_ENV
          if [ -z $TAG ]; then
          	TAG=${SHA}
          fi
          echo "HOF_SHA=${SHA}" >> $GITHUB_ENV
          echo "HOF_TAG=${TAG}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: formatters/tools/${{ matrix.formatter }}
          file: formatters/tools/${{ matrix.formatter }}/Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          tags: hofstadter/fmt-${{ matrix.formatter }}:${{ env.HOF_SHA }},hofstadter/fmt-${{ matrix.formatter }}:${{ env.HOF_TAG }}
    services: {}
