name: hof
"on":
  - push
  - pull_request
  - workflow_dispatch
env:
  HOF_TELEMETRY_DISABLED: "1"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.19.x
          - 1.20.x
        os:
          - ubuntu-latest
          - macos-latest
    environment: hof mod testing
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: |-
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.go-version }}-
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Vars
        id: vars
        run: |-
          SHA=${GITHUB_SHA::8}
          TAG=$(git tag --points-at HEAD)
          echo "HOF_FMT_VERSION=${TAG}" >> $GITHUB_ENV
          if [ -z $TAG ]; then
          	TAG=${SHA}
          fi
          echo "HOF_SHA=${SHA}" >> $GITHUB_ENV
          echo "HOF_TAG=${TAG}" >> $GITHUB_ENV
      - name: Fetch Go deps
        run: go mod download
      - name: Build CLI
        run: go install ./cmd/hof
      - name: Set up Docker BuildX
        if: ${{ !startsWith( runner.os, 'macos') }}
        uses: docker/setup-buildx-action@v2
      - name: Test Compatibility
        if: ${{ !startsWith( runner.os, 'macos') }}
        run: |-
          docker version
          go run test/docker/main.go
      - name: Build Formatters
        run: |-
          make formatters
          hof fmt info
        if: ${{ !startsWith( runner.os, 'macos') }}
      - name: test/self
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
        run: |-
          # self: gen -> diff
          set -e

          # mods stuff & gen
          hof mod tidy
          hof mod vendor
          hof gen

          # should have no diff
          git diff --exit-code
      - name: Start formatters
        run: |-
          hof fmt start
          hof fmt info
        if: ${{ !startsWith( runner.os, 'macos') }}
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
      - name: test/gen
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
        run: hof flow @test/gen ./test.cue
      - name: test/render
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
        run: hof flow @test/render ./test.cue
      - name: test/structural
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
        run: hof flow @test/st ./test.cue
      - name: test/flow
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
        run: hof flow -f test/flow ./test.cue
      - name: test/mod
        run: hof flow -f test/mod ./test.cue
        env:
          GITLAB_TOKEN: ${{secrets.GITLAB_TOKEN}}
          BITBUCKET_USERNAME: hofstadter
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          BITBUCKET_PASSWORD: ${{secrets.BITBUCKET_TOKEN}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
      - name: test/fmt
        run: |-
          hof fmt info
          hof flow -f test/fmt ./test.cue
        if: ${{ !startsWith( runner.os, 'macos') }}
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
    services: {}
