name: release (docs)
"on":
  push:
    tags:
      - docs-*
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Vars
        id: vars
        run: |-
          SHA=${GITHUB_SHA::8}
          TAG=$(git tag --points-at HEAD)
          echo "HOF_FMT_VERSION=${TAG}" >> $GITHUB_ENV
          if [ -z $TAG ]; then
          	TAG=${SHA}
          fi
          echo "HOF_SHA=${SHA}" >> $GITHUB_ENV
          echo "HOF_TAG=${TAG}" >> $GITHUB_ENV
      - name: Setup
        run: go install ./cmd/hof
    strategy: {}
    services: {}
