name: release
"on":
  push:
    branches-ignore:
      - '*'
      - '!_dev'
    tags:
      - v*
jobs:
  formatter:
    environment: hof mod testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        formatter:
          - prettier
          - csharpier
          - black
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Vars
        id: vars
        run: |-
          SHA=${GITHUB_SHA::8}
          TAG=$(git tag --points-at HEAD)
          if [ -z $TAG ]; then
          	TAG=${SHA}
          fi
          echo "HOF_SHA=${SHA}" >> $GITHUB_ENV
          echo "HOF_TAG=${TAG}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HOF_DOCKER_USER }}
          password: ${{ secrets.HOF_DOCKER_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: formatters/tools/${{ matrix.formatter }}
          file: formatters/tools/${{ matrix.formatter }}/Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hofstadter-io/fmt-${{ matrix.formatter }}:${{ env.HOF_SHA }},hofstadter-io/fmt-${{ matrix.formatter }}:${{ env.HOF_TAG }}
    services: {}
