name: test_mod
"on":
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.19.x
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    environment: hof mod testing
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build CLI
        run: go install ./cmd/hof
      - name: Run mod tests
        run: hof flow -f test/mods ./test.cue
        env:
          HOFMOD_SSHKEY: ${{secrets.HOFMOD_SSHKEY}}
          GITHUB_TOKEN: ${{secrets.HOFMOD_TOKEN}}
          GITLAB_TOKEN: ${{secrets.GITLAB_TOKEN}}
          BITBUCKET_USERNAME: hofstadter
          BITBUCKET_PASSWORD: ${{secrets.BITBUCKET_TOKEN}}
    services: {}
