name: test_flow
"on":
  pull_request:
    paths:
      - .github/workflows/test_flow.*
      - flow/**
  push:
    paths:
      - .github/workflows/test_flow.*
      - flow/**
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.19.x
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    environment: hof flow testing
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build CLI
        run: go install ./cmd/hof
      - name: Run mod tests
        run: hof flow -f test/flow ./test.cue
    services: {}
